// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjSGJ1bj7OKTjKK2uzAHF85Rq83m0sq5M',
    appId: '1:330121166040:web:d2660e765b1cbc4cd5abad',
    messagingSenderId: '330121166040',
    projectId: 'schedule-app-df4ef',
    authDomain: 'schedule-app-df4ef.firebaseapp.com',
    storageBucket: 'schedule-app-df4ef.firebasestorage.app',
    measurementId: 'G-38B0Q3VNHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhfx4-RXiAoO3xLGAUd_ENFgbqIaWS9VQ',
    appId: '1:330121166040:android:900bba05f37191e3d5abad',
    messagingSenderId: '330121166040',
    projectId: 'schedule-app-df4ef',
    storageBucket: 'schedule-app-df4ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhJTJnqHI8Oc_u4qwmJbNc0lA4vId-5nk',
    appId: '1:330121166040:ios:01c1a6509c035d11d5abad',
    messagingSenderId: '330121166040',
    projectId: 'schedule-app-df4ef',
    storageBucket: 'schedule-app-df4ef.firebasestorage.app',
    iosBundleId: 'com.example.scheduleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhJTJnqHI8Oc_u4qwmJbNc0lA4vId-5nk',
    appId: '1:330121166040:ios:01c1a6509c035d11d5abad',
    messagingSenderId: '330121166040',
    projectId: 'schedule-app-df4ef',
    storageBucket: 'schedule-app-df4ef.firebasestorage.app',
    iosBundleId: 'com.example.scheduleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjSGJ1bj7OKTjKK2uzAHF85Rq83m0sq5M',
    appId: '1:330121166040:web:f8cdf4f0ce417797d5abad',
    messagingSenderId: '330121166040',
    projectId: 'schedule-app-df4ef',
    authDomain: 'schedule-app-df4ef.firebaseapp.com',
    storageBucket: 'schedule-app-df4ef.firebasestorage.app',
    measurementId: 'G-J0THESFS5H',
  );
}
